name: Hello World Action
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      name:
        description: 'Who to greet'
        required: true
        default: 'World'

jobs:
  hello-world:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run custom hello world action
        uses: ./.github/actions/hello-world
        id: hello
        with:
          name: ${{ github.event.pull_request.user.login || github.event.inputs.name || 'World' }}

      - name: Show output time
        run: echo "Action was run at ${{ steps.hello.outputs.time }}"

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        env:
          TIME: ${{ steps.hello.outputs.time }}
        with:
          script: |
            // Debug information
            console.log('Event name:', context.eventName);
            console.log('Action:', context.action);
            console.log('Repository:', context.repo.owner + '/' + context.repo.name);
            console.log('PR number:', context.payload.pull_request.number);
            console.log('PR title:', context.payload.pull_request.title);
            
            try {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.name,
                issue_number: context.payload.pull_request.number,
                body: `Hello @${context.payload.pull_request.user.login}! Action was run at ${process.env.TIME}`
              });
            } catch (error) {
              console.log('Error details:', error);
              core.setFailed(error.message);
            }