name: Hello World Action
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      name:
        description: 'Who to greet'
        required: true
        default: 'World'

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run custom hello world action
        uses: ./.github/actions/hello-world
        id: hello
        with:
          name: ${{ github.event.pull_request.user.login || github.event.inputs.name || 'World' }}

      - name: Show output time
        run: echo "Action was run at ${{ steps.hello.outputs.time }}"

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: `Hello @${context.payload.pull_request.user.login}! Action was run at ${steps.hello.outputs.time}`
            })